services:
    _defaults:
        public: false
        autowire: true
        autoconfigure: true

    Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger:
        alias: surfnet_saml.logger

    Surfnet\SamlBundle\Security\Authentication\Handler\SuccessHandler:
        arguments:
            - '@security.http_utils'
            - []
            - '@logger'

    Surfnet\SamlBundle\Security\Authentication\Handler\FailureHandler:
        arguments:
            - '@kernel'
            - '@security.http_utils'
            - [ ]
            - '@logger'
