services:
    # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
    _defaults:
        public: true

    surfnet_saml.saml.attribute_dictionary:
        class: Surfnet\SamlBundle\SAML2\Attribute\AttributeDictionary
        arguments:
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration

    Surfnet\SamlBundle\SAML2\Attribute\AttributeDictionary:
        alias: surfnet_saml.saml.attribute_dictionary

    surfnet_saml.configuration.metadata:
        class: Surfnet\SamlBundle\Metadata\MetadataConfiguration

    Surfnet\SamlBundle\Metadata\MetadataConfiguration:
        alias: surfnet_saml.configuration.metadata

    surfnet_saml.configuration.hosted_entities:
        public: false
        class: Surfnet\SamlBundle\Entity\HostedEntities
        arguments:
            - '@router'
            - '@request_stack'
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration
            - null # Replaced in the Surfnet\SamlBundle\DependencyInjection\SurfnetSamlExtension based on configuration

    Surfnet\SamlBundle\Entity\HostedEntities:
        alias: surfnet_saml.configuration.hosted_entities
        public: false

    surfnet_saml.hosted.service_provider:
        class:   Surfnet\SamlBundle\Entity\ServiceProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getServiceProvider]

    Surfnet\SamlBundle\Entity\ServiceProvider:
        alias: surfnet_saml.hosted.service_provider

    surfnet_saml.hosted.identity_provider:
        class:   Surfnet\SamlBundle\Entity\IdentityProvider
        factory: ['@surfnet_saml.configuration.hosted_entities', getIdentityProvider]

    Surfnet\SamlBundle\Entity\IdentityProvider:
        alias: surfnet_saml.hosted.identity_provider

    surfnet_saml.http.binding_factory:
        class: Surfnet\SamlBundle\Http\HttpBindingFactory
        arguments:
            - '@surfnet_saml.http.redirect_binding'
            - '@surfnet_saml.http.post_binding'

    Surfnet\SamlBundle\Http\HttpBindingFactory:
        alias: surfnet_saml.http.binding_factory

    surfnet_saml.http.redirect_binding:
        class: Surfnet\SamlBundle\Http\RedirectBinding
        arguments:
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'

    Surfnet\SamlBundle\Http\RedirectBinding:
        alias: surfnet_saml.http.redirect_binding

    surfnet_saml.http.post_binding:
        class: Surfnet\SamlBundle\Http\PostBinding
        arguments:
            - '@surfnet_saml.saml2.response_processor'
            - '@surfnet_saml.signing.signature_verifier'
            - '@?surfnet_saml.entity.entity_repository'

    Surfnet\SamlBundle\Http\PostBinding:
        alias: surfnet_saml.http.post_binding

    surfnet_saml.metadata_factory:
        class: Surfnet\SamlBundle\Metadata\MetadataFactory
        arguments:
            - '@twig'
            - '@router'
            - '@surfnet_saml.signing_service'
            - '@surfnet_saml.configuration.metadata'

    Surfnet\SamlBundle\Metadata\MetadataFactory:
        alias: surfnet_saml.metadata_factory

    surfnet_saml.signing_service:
        class: Surfnet\SamlBundle\Service\SigningService
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@surfnet_saml.saml2.privatekeyloader'

    Surfnet\SamlBundle\Service\SigningService:
        alias: surfnet_saml.signing_service

    surfnet_saml.signing.signature_verifier:
        class: Surfnet\SamlBundle\Signing\SignatureVerifier
        arguments:
            - '@surfnet_saml.saml2.keyloader'
            - '@logger'

    Surfnet\SamlBundle\Signing\SignatureVerifier:
        alias: surfnet_saml.signing.signature_verifier

    surfnet_saml.saml2.bridge_container:
        class: Surfnet\SamlBundle\SAML2\BridgeContainer
        arguments:
            - '@logger'

    Surfnet\SamlBundle\SAML2\BridgeContainer:
        alias: surfnet_saml.saml2.bridge_container

    surfnet_saml.saml2.keyloader:
        public: false
        class: SAML2\Certificate\KeyLoader

    SAML2\Certificate\KeyLoader:
        public: false
        alias: surfnet_saml.saml2.keyloader

    surfnet_saml.saml2.privatekeyloader:
        public: false
        class: SAML2\Certificate\PrivateKeyLoader

    SAML2\Certificate\PrivateKeyLoader:
        public: false
        alias: surfnet_saml.saml2.privatekeyloader

    surfnet_saml.saml2.response_processor:
        public: false
        class: SAML2\Response\Processor
        arguments:
            - '@logger'

    SAML2\Response\Processor:
        public: false
        alias: surfnet_saml.saml2.response_processor

    surfnet_saml.logger:
        class: Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger
        arguments:
            - '@logger'

    Surfnet\SamlBundle\Monolog\SamlAuthenticationLogger:
        alias: surfnet_saml.logger

    Surfnet\SamlBundle\Security\Authentication\Handler\ProcessSamlAuthenticationHandler:
        arguments:
            - '@Surfnet\SamlBundle\Security\Authentication\SamlInteractionProvider'
            - '@Surfnet\SamlBundle\Security\Authentication\Session\SessionStorage'
            - '@surfnet_saml.logger'

    Surfnet\SamlBundle\Security\Authentication\SamlInteractionProvider:
        arguments:
            - '@surfnet_saml.hosted.service_provider'
            - '@surfnet_saml.remote.idp'
            - '@surfnet_saml.http.redirect_binding'
            - '@surfnet_saml.http.post_binding'
            - '@Surfnet\SamlBundle\Security\Authentication\Session\SessionStorage'

    Surfnet\SamlBundle\Security\Authentication\Handler\SuccessHandler:
        arguments:
            - '@security.http_utils'
            - []
            - '@logger'

    Surfnet\SamlBundle\Security\Authentication\Handler\FailureHandler:
        arguments:
            - '@kernel'
            - '@security.http_utils'
            - [ ]
            - '@logger'

    Surfnet\SamlBundle\Security\Authentication\SamlAuthenticator:
        arguments:
            - '@surfnet_saml.remote.idp'
            - '@surfnet_saml.hosted.service_provider'
            - '@surfnet_saml.http.redirect_binding'
            - '@Surfnet\SamlBundle\Security\Authentication\Session\SessionStorage'
            - '@Surfnet\SamlBundle\Security\Authentication\Handler\ProcessSamlAuthenticationHandler'
            - '@Surfnet\SamlBundle\Security\Authentication\Handler\SuccessHandler'
            - '@Surfnet\SamlBundle\Security\Authentication\Handler\FailureHandler'
            - '@surfnet_saml.saml_provider'
            - '@router'
            - '@logger'
            - '%env(acs_location_route_name)%'

    Surfnet\SamlBundle\Security\Authentication\Session\SessionStorage:
        arguments:
            - '@request_stack'
